apiVersion: backstage.io/v1alpha1
kind: System
metadata:
    name: github2-test
    description: AWS account 913524924452 for test in OU github2
    environment: test
    annotations:
      aws-parent-ou-id: 'ou-tdye-ur2beps1'
      aws-account-id: '913524924452'
      aws-account-region: eu-central-1
spec:
    owner: guests
    domain: github2
