# AUTOGENERATED BY TERRAFORM - THIS FILE NEEDS TO BE COMMITTED TO YOUR REPO
bucket         = "terraform-802306197541"
region         = "eu-central-1"
dynamodb_table = "terraform-lock-802306197541"
encrypt        = true