apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: bingo
  description: Terraform generated OU bingo
  annotations:
    ou_id: ou-tdye-curuuwpr
    type: workload
spec:
    owner: guests